language: generic
dist: bionic
sudo: required
services:
- docker
script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE
env:
- DOCKER_IMAGE=fedora:34
- DOCKER_IMAGE=fedora:rawhide
matrix:
  allow_failures:
  - env: DOCKER_IMAGE=fedora:rawhide
before_deploy:
- openssl aes-256-cbc -K $encrypted_3efc8b0ffc6e_key -iv $encrypted_3efc8b0ffc6e_iv -in .copr.enc -out .copr -d
deploy:
  skip_cleanup: true
  provider: script
  script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --chroot fedora-34-x86_64 --nowait simc/stable arkimaps.spec"
  true:
    branch: master
    condition: $DOCKER_IMAGE = fedora:34
